"""Add role column to users

Revision ID: 01c8887d5e75
Revises: ea560e676485
Create Date: 2025-12-09 23:48:53.543223

"""
from alembic import op
import sqlalchemy as sa


revision = '01c8887d5e75'
down_revision = 'ea560e676485'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), server_default='FARMER', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
