"""Link expenditure to inventory

Revision ID: 25ac35a4896b
Revises: df2051f9bcb7
Create Date: 2025-12-10 00:00:23.820200

"""
from alembic import op
import sqlalchemy as sa


revision = '25ac35a4896b'
down_revision = '01c8887d5e75'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenditures', sa.Column('inventory_item_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expenditures_inventory_item_id'), 'expenditures', ['inventory_item_id'], unique=False)
    op.create_foreign_key(op.f('fk_expenditures_inventory_item_id_inventory_items'), 'expenditures', 'inventory_items', ['inventory_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_expenditures_inventory_item_id_inventory_items'), 'expenditures', type_='foreignkey')
    op.drop_index(op.f('ix_expenditures_inventory_item_id'), table_name='expenditures')
    op.drop_column('expenditures', 'inventory_item_id')
    # ### end Alembic commands ###
