"""create inventory_history table

Revision ID: 334dab4bd164
Revises: 42ca4edb20a3
Create Date: 2025-12-10 00:19:57.193442

"""
from alembic import op
import sqlalchemy as sa


revision = '334dab4bd164'
down_revision = '42ca4edb20a3'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_history',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('quantity_change', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_inventory_history_inventory_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_history'))
    )
    op.create_index(op.f('ix_inventory_history_inventory_item_id'), 'inventory_history', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_history_user_id'), 'inventory_history', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_history_user_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_inventory_item_id'), table_name='inventory_history')
    op.drop_table('inventory_history')
    # ### end Alembic commands ###
