"""Add is_superuser to users

Revision ID: 3f0262fe06e5
Revises: b9cea8597f4f
Create Date: 2025-12-08 15:41:57.328951

"""
from alembic import op
import sqlalchemy as sa


revision = '3f0262fe06e5'
down_revision = 'b9cea8597f4f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_index(op.f('ix_weight_measurement_events_event_date'), table_name='weight_measurement_events')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weight_measurement_events_event_date'), 'weight_measurement_events', ['event_date'], unique=False)
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
