"""make alert flock_id nullable

Revision ID: 42ca4edb20a3
Revises: 25ac35a4896b
Create Date: 2025-12-10 00:16:12.031997

"""
from alembic import op
import sqlalchemy as sa


revision = '42ca4edb20a3'
down_revision = '25ac35a4896b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'flock_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'flock_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
