"""add_performance_indexes

Revision ID: 477eb95ed329
Revises: a1b2c3d4e5f6
Create Date: 2026-04-21 21:52:59.264897

"""
from alembic import op
import sqlalchemy as sa


revision = '477eb95ed329'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_updated_at'), 'alerts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_updated_at'), 'api_keys', ['updated_at'], unique=False)
    op.create_index(op.f('ix_biosecurity_checks_created_at'), 'biosecurity_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_biosecurity_checks_updated_at'), 'biosecurity_checks', ['updated_at'], unique=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_updated_at'), 'customers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_daily_checks_created_at'), 'daily_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_daily_checks_updated_at'), 'daily_checks', ['updated_at'], unique=False)
    op.create_index(op.f('ix_employees_created_at'), 'employees', ['created_at'], unique=False)
    op.create_index(op.f('ix_employees_updated_at'), 'employees', ['updated_at'], unique=False)
    op.alter_column('expenditures', 'related_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID of the source event (e.g. FeedEvent ID)',
               existing_nullable=True)
    op.alter_column('expenditures', 'related_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of source event: feed, vaccination, flock_placement',
               existing_nullable=True)
    op.create_index(op.f('ix_expenditures_created_at'), 'expenditures', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenditures_date'), 'expenditures', ['date'], unique=False)
    op.create_index(op.f('ix_expenditures_updated_at'), 'expenditures', ['updated_at'], unique=False)
    op.create_index(op.f('ix_farm_members_created_at'), 'farm_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_farm_members_updated_at'), 'farm_members', ['updated_at'], unique=False)
    op.create_index(op.f('ix_farms_created_at'), 'farms', ['created_at'], unique=False)
    op.create_index(op.f('ix_farms_updated_at'), 'farms', ['updated_at'], unique=False)
    op.create_index(op.f('ix_feed_consumption_events_created_at'), 'feed_consumption_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_consumption_events_updated_at'), 'feed_consumption_events', ['updated_at'], unique=False)
    op.create_index(op.f('ix_flocks_created_at'), 'flocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_flocks_start_date'), 'flocks', ['start_date'], unique=False)
    op.create_index(op.f('ix_flocks_updated_at'), 'flocks', ['updated_at'], unique=False)
    op.create_index(op.f('ix_inventory_history_created_at'), 'inventory_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_history_updated_at'), 'inventory_history', ['updated_at'], unique=False)
    op.create_index(op.f('ix_inventory_items_created_at'), 'inventory_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_items_updated_at'), 'inventory_items', ['updated_at'], unique=False)
    op.create_index(op.f('ix_market_prices_created_at'), 'market_prices', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_prices_updated_at'), 'market_prices', ['updated_at'], unique=False)
    op.create_index(op.f('ix_mortality_events_created_at'), 'mortality_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_mortality_events_updated_at'), 'mortality_events', ['updated_at'], unique=False)
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_resources_updated_at'), 'resources', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sales_created_at'), 'sales', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index(op.f('ix_sales_updated_at'), 'sales', ['updated_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_created_at'), 'scheduled_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_updated_at'), 'scheduled_tasks', ['updated_at'], unique=False)
    op.create_index(op.f('ix_subscription_plans_created_at'), 'subscription_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_plans_updated_at'), 'subscription_plans', ['updated_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_updated_at'), 'subscriptions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_index(op.f('ix_suppliers_updated_at'), 'suppliers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_system_config_created_at'), 'system_config', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_config_updated_at'), 'system_config', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_settings_created_at'), 'user_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_settings_updated_at'), 'user_settings', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_vaccination_events_created_at'), 'vaccination_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_vaccination_events_updated_at'), 'vaccination_events', ['updated_at'], unique=False)
    op.create_index(op.f('ix_vet_consultations_created_at'), 'vet_consultations', ['created_at'], unique=False)
    op.create_index(op.f('ix_vet_consultations_updated_at'), 'vet_consultations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_weight_measurement_events_created_at'), 'weight_measurement_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_weight_measurement_events_updated_at'), 'weight_measurement_events', ['updated_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_measurement_events_updated_at'), table_name='weight_measurement_events')
    op.drop_index(op.f('ix_weight_measurement_events_created_at'), table_name='weight_measurement_events')
    op.drop_index(op.f('ix_vet_consultations_updated_at'), table_name='vet_consultations')
    op.drop_index(op.f('ix_vet_consultations_created_at'), table_name='vet_consultations')
    op.drop_index(op.f('ix_vaccination_events_updated_at'), table_name='vaccination_events')
    op.drop_index(op.f('ix_vaccination_events_created_at'), table_name='vaccination_events')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_user_settings_updated_at'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_created_at'), table_name='user_settings')
    op.drop_index(op.f('ix_system_config_updated_at'), table_name='system_config')
    op.drop_index(op.f('ix_system_config_created_at'), table_name='system_config')
    op.drop_index(op.f('ix_suppliers_updated_at'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_index(op.f('ix_subscriptions_updated_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscription_plans_updated_at'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_created_at'), table_name='subscription_plans')
    op.drop_index(op.f('ix_scheduled_tasks_updated_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_created_at'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_sales_updated_at'), table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_created_at'), table_name='sales')
    op.drop_index(op.f('ix_resources_updated_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_index(op.f('ix_mortality_events_updated_at'), table_name='mortality_events')
    op.drop_index(op.f('ix_mortality_events_created_at'), table_name='mortality_events')
    op.drop_index(op.f('ix_market_prices_updated_at'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_created_at'), table_name='market_prices')
    op.drop_index(op.f('ix_inventory_items_updated_at'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_created_at'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_history_updated_at'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_created_at'), table_name='inventory_history')
    op.drop_index(op.f('ix_flocks_updated_at'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_start_date'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_created_at'), table_name='flocks')
    op.drop_index(op.f('ix_feed_consumption_events_updated_at'), table_name='feed_consumption_events')
    op.drop_index(op.f('ix_feed_consumption_events_created_at'), table_name='feed_consumption_events')
    op.drop_index(op.f('ix_farms_updated_at'), table_name='farms')
    op.drop_index(op.f('ix_farms_created_at'), table_name='farms')
    op.drop_index(op.f('ix_farm_members_updated_at'), table_name='farm_members')
    op.drop_index(op.f('ix_farm_members_created_at'), table_name='farm_members')
    op.drop_index(op.f('ix_expenditures_updated_at'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_date'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_created_at'), table_name='expenditures')
    op.alter_column('expenditures', 'related_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of source event: feed, vaccination, flock_placement',
               existing_nullable=True)
    op.alter_column('expenditures', 'related_id',
               existing_type=sa.UUID(),
               comment='ID of the source event (e.g. FeedEvent ID)',
               existing_nullable=True)
    op.drop_index(op.f('ix_employees_updated_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_at'), table_name='employees')
    op.drop_index(op.f('ix_daily_checks_updated_at'), table_name='daily_checks')
    op.drop_index(op.f('ix_daily_checks_created_at'), table_name='daily_checks')
    op.drop_index(op.f('ix_customers_updated_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_biosecurity_checks_updated_at'), table_name='biosecurity_checks')
    op.drop_index(op.f('ix_biosecurity_checks_created_at'), table_name='biosecurity_checks')
    op.drop_index(op.f('ix_api_keys_updated_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_index(op.f('ix_alerts_updated_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    # ### end Alembic commands ###
