"""Add_full_features

Revision ID: 5091c024f4b4
Revises: 76a056426884
Create Date: 2025-12-07 11:27:47.532915

"""
from alembic import op
import sqlalchemy as sa


revision = '5091c024f4b4'
down_revision = '76a056426884'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biosecurity_checks',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_biosecurity_checks_farmer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biosecurity_checks'))
    )
    op.create_index(op.f('ix_biosecurity_checks_farmer_id'), 'biosecurity_checks', ['farmer_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('minimum_stock', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_unit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('last_restocked', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventory_items_positive_quantity')),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_inventory_items_farmer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    op.create_index(op.f('ix_inventory_items_farmer_id'), 'inventory_items', ['farmer_id'], unique=False)
    op.create_table('expenditures',
    sa.Column('flock_id', sa.UUID(), nullable=True),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('receipt_image', sa.String(length=255), nullable=True),
    sa.Column('mpesa_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_expenditures_positive_amount')),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_expenditures_farmer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_expenditures_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenditures'))
    )
    op.create_index(op.f('ix_expenditures_farmer_id'), 'expenditures', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_expenditures_flock_id'), 'expenditures', ['flock_id'], unique=False)
    op.create_table('sales',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_bird', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mpesa_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('average_weight_grams', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sales_positive_quantity')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_sales_positive_total_amount')),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_sales_farmer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_sales_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales'))
    )
    op.create_index(op.f('ix_sales_farmer_id'), 'sales', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_sales_flock_id'), 'sales', ['flock_id'], unique=False)
    op.add_column('flocks', sa.Column('cost_per_bird', sa.Integer(), nullable=True))
    op.add_column('flocks', sa.Column('total_acquisition_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flocks', 'total_acquisition_cost')
    op.drop_column('flocks', 'cost_per_bird')
    op.drop_index(op.f('ix_sales_flock_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_farmer_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_expenditures_flock_id'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_farmer_id'), table_name='expenditures')
    op.drop_table('expenditures')
    op.drop_index(op.f('ix_inventory_items_farmer_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_biosecurity_checks_farmer_id'), table_name='biosecurity_checks')
    op.drop_table('biosecurity_checks')
    # ### end Alembic commands ###
