"""Add subscription table

Revision ID: 665ba203e0cf
Revises: e4c283e9ade4
Create Date: 2025-12-09 14:42:51.932348

"""
from alembic import op
import sqlalchemy as sa


revision = '665ba203e0cf'
down_revision = 'e4c283e9ade4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
