"""add_show_discount_to_plans

Revision ID: 6c42fc395c02
Revises: a8b2c3d4e5f6
Create Date: 2026-03-26 13:22:24.645310

"""
from alembic import op
import sqlalchemy as sa


revision = '6c42fc395c02'
down_revision = 'a8b2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('show_discount', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'show_discount')
    # ### end Alembic commands ###
