"""make_email_and_password_nullable

Revision ID: 71e63daf3e91
Revises: 03fa41b70882
Create Date: 2026-03-23 21:27:58.115254

"""
from alembic import op
import sqlalchemy as sa


revision = '71e63daf3e91'
down_revision = '03fa41b70882'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_checkout_request_id'), table_name='sales')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_sales_checkout_request_id'), 'sales', ['checkout_request_id'], unique=True)
    # ### end Alembic commands ###
