"""Initial schema with all tables

Revision ID: 76a056426884
Revises: 
Create Date: 2025-12-07 05:16:57.974378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '76a056426884'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('flocks',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('hatchery_source', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('initial_count', sa.Integer(), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'terminated')", name=op.f('ck_flocks_valid_status')),
    sa.CheckConstraint('initial_count > 0', name=op.f('ck_flocks_positive_initial_count')),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_flocks_farmer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flocks'))
    )
    op.create_index(op.f('ix_flocks_farmer_id'), 'flocks', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_flocks_status'), 'flocks', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_alerts_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_flock_id'), 'alerts', ['flock_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('daily_checks',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('check_time', sa.Time(), nullable=True),
    sa.Column('temperature_celsius', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('chick_behavior', sa.String(length=50), nullable=True),
    sa.Column('litter_condition', sa.String(length=50), nullable=True),
    sa.Column('feed_level', sa.String(length=50), nullable=True),
    sa.Column('water_level', sa.String(length=50), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("chick_behavior IN ('normal', 'huddling', 'dispersed', 'panting', 'lethargic')", name=op.f('ck_daily_checks_valid_chick_behavior')),
    sa.CheckConstraint("feed_level IN ('full', 'adequate', 'low', 'empty')", name=op.f('ck_daily_checks_valid_feed_level')),
    sa.CheckConstraint("litter_condition IN ('dry', 'damp', 'wet', 'caked')", name=op.f('ck_daily_checks_valid_litter_condition')),
    sa.CheckConstraint("water_level IN ('full', 'adequate', 'low', 'empty')", name=op.f('ck_daily_checks_valid_water_level')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_daily_checks_flock_id_flocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_daily_checks_recorded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_checks')),
    sa.UniqueConstraint('flock_id', 'check_date', name='uq_flock_daily_check')
    )
    op.create_index(op.f('ix_daily_checks_check_date'), 'daily_checks', ['check_date'], unique=False)
    op.create_index(op.f('ix_daily_checks_flock_id'), 'daily_checks', ['flock_id'], unique=False)
    op.create_table('feed_consumption_events',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=True),
    sa.Column('quantity_kg', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cost_ksh', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("feed_type IN ('starter', 'grower', 'finisher')", name=op.f('ck_feed_consumption_events_valid_feed_type')),
    sa.CheckConstraint('quantity_kg > 0', name=op.f('ck_feed_consumption_events_positive_feed_quantity')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_feed_consumption_events_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_consumption_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_feed_consumption_events_event_id'))
    )
    op.create_index(op.f('ix_feed_consumption_events_event_date'), 'feed_consumption_events', ['event_date'], unique=False)
    op.create_index('ix_feed_consumption_events_event_id', 'feed_consumption_events', ['event_id'], unique=True)
    op.create_index('ix_feed_consumption_events_flock_id', 'feed_consumption_events', ['flock_id'], unique=False)
    op.create_table('mortality_events',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=100), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('count > 0', name=op.f('ck_mortality_events_positive_mortality_count')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_mortality_events_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mortality_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_mortality_events_event_id'))
    )
    op.create_index(op.f('ix_mortality_events_event_date'), 'mortality_events', ['event_date'], unique=False)
    op.create_index('ix_mortality_events_event_id', 'mortality_events', ['event_id'], unique=True)
    op.create_index('ix_mortality_events_flock_id', 'mortality_events', ['flock_id'], unique=False)
    op.create_table('vaccination_events',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('disease_target', sa.String(length=100), nullable=False),
    sa.Column('administration_method', sa.String(length=50), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('administered_by', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("administration_method IN ('drinking_water', 'eye_drop', 'injection', 'spray')", name=op.f('ck_vaccination_events_valid_administration_method')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_vaccination_events_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaccination_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_vaccination_events_event_id'))
    )
    op.create_index(op.f('ix_vaccination_events_event_date'), 'vaccination_events', ['event_date'], unique=False)
    op.create_index('ix_vaccination_events_event_id', 'vaccination_events', ['event_id'], unique=True)
    op.create_index('ix_vaccination_events_flock_id', 'vaccination_events', ['flock_id'], unique=False)
    op.create_index('ix_vaccination_events_next_due_date', 'vaccination_events', ['next_due_date'], unique=False)
    op.create_table('weight_measurement_events',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('average_weight_grams', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_weight_grams', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('max_weight_grams', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('average_weight_grams > 0', name=op.f('ck_weight_measurement_events_positive_average_weight')),
    sa.CheckConstraint('sample_size > 0', name=op.f('ck_weight_measurement_events_positive_sample_size')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_weight_measurement_events_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_measurement_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_weight_measurement_events_event_id'))
    )
    op.create_index(op.f('ix_weight_measurement_events_event_date'), 'weight_measurement_events', ['event_date'], unique=False)
    op.create_index('ix_weight_measurement_events_event_id', 'weight_measurement_events', ['event_id'], unique=True)
    op.create_index('ix_weight_measurement_events_flock_id', 'weight_measurement_events', ['flock_id'], unique=False)
    op.create_index('ix_weight_measurement_events_measurement_date', 'weight_measurement_events', ['measurement_date'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weight_measurement_events_measurement_date', table_name='weight_measurement_events')
    op.drop_index('ix_weight_measurement_events_flock_id', table_name='weight_measurement_events')
    op.drop_index('ix_weight_measurement_events_event_id', table_name='weight_measurement_events')
    op.drop_index(op.f('ix_weight_measurement_events_event_date'), table_name='weight_measurement_events')
    op.drop_table('weight_measurement_events')
    op.drop_index('ix_vaccination_events_next_due_date', table_name='vaccination_events')
    op.drop_index('ix_vaccination_events_flock_id', table_name='vaccination_events')
    op.drop_index('ix_vaccination_events_event_id', table_name='vaccination_events')
    op.drop_index(op.f('ix_vaccination_events_event_date'), table_name='vaccination_events')
    op.drop_table('vaccination_events')
    op.drop_index('ix_mortality_events_flock_id', table_name='mortality_events')
    op.drop_index('ix_mortality_events_event_id', table_name='mortality_events')
    op.drop_index(op.f('ix_mortality_events_event_date'), table_name='mortality_events')
    op.drop_table('mortality_events')
    op.drop_index('ix_feed_consumption_events_flock_id', table_name='feed_consumption_events')
    op.drop_index('ix_feed_consumption_events_event_id', table_name='feed_consumption_events')
    op.drop_index(op.f('ix_feed_consumption_events_event_date'), table_name='feed_consumption_events')
    op.drop_table('feed_consumption_events')
    op.drop_index(op.f('ix_daily_checks_flock_id'), table_name='daily_checks')
    op.drop_index(op.f('ix_daily_checks_check_date'), table_name='daily_checks')
    op.drop_table('daily_checks')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_flock_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_flocks_status'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_farmer_id'), table_name='flocks')
    op.drop_table('flocks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
