"""Add SubscriptionPlan model

Revision ID: a8b2c3d4e5f6
Revises: 71e63daf3e91
Create Date: 2026-03-25

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = 'a8b2c3d4e5f6'
down_revision = '71e63daf3e91'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('monthly_price', sa.String(), nullable=False, server_default='0'),
    sa.Column('yearly_price', sa.String(), nullable=False, server_default='0'),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'),
    sa.Column('popular', sa.Boolean(), nullable=True, server_default='false'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_plan_type'), 'subscription_plans', ['plan_type'], unique=True)
    
    # Seed initial plans
    # Note: Using uuid_generate_v4() if available, otherwise just use fixed UUID strings for consistency
    op.execute("""
        INSERT INTO subscription_plans (id, created_at, updated_at, plan_type, name, description, monthly_price, yearly_price, features, is_active, popular)
        VALUES 
        ('550e8400-e29b-41d4-a716-446655440000', now(), now(), 'STARTER', 'Starter', 'Core flock management for small farms.', '0', '0', '["mortality", "feed", "weight"]'::jsonb, true, false),
        ('550e8400-e29b-41d4-a716-446655440001', now(), now(), 'PROFESSIONAL', 'Professional', 'Advanced analytics and inventory for growing farms.', '3500', '35000', '["mortality", "feed", "weight", "inventory", "financials", "market_prices", "vet_consults", "reports_export"]'::jsonb, true, true),
        ('550e8400-e29b-41d4-a716-446655440002', now(), now(), 'ENTERPRISE', 'Enterprise', 'Full AI intelligence and multi-farm support.', '10000', '100000', '["mortality", "feed", "weight", "inventory", "financials", "market_prices", "vet_consults", "reports_export", "ai_advisory", "ai_chat", "multi_farm", "audit_logs"]'::jsonb, true, false)
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_plan_type'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
