"""Update flock model

Revision ID: b044cf7a3c33
Revises: da1afc939ab6
Create Date: 2025-12-07 14:46:51.476487

"""
from alembic import op
import sqlalchemy as sa


revision = 'b044cf7a3c33'
down_revision = 'da1afc939ab6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flocks', sa.Column('source_location', sa.String(length=255), nullable=True))
    op.alter_column('flocks', 'cost_per_bird',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('flocks', 'total_acquisition_cost',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flocks', 'total_acquisition_cost',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('flocks', 'cost_per_bird',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('flocks', 'source_location')
    # ### end Alembic commands ###
