"""Add vet and market tables

Revision ID: b9cea8597f4f
Revises: b044cf7a3c33
Create Date: 2025-12-07 14:56:27.510142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b9cea8597f4f'
down_revision = 'b044cf7a3c33'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('price_per_kg', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_per_bird', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price_per_kg > 0', name=op.f('ck_market_prices_positive_price_per_kg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_prices'))
    )
    op.create_index(op.f('ix_market_prices_county'), 'market_prices', ['county'], unique=False)
    op.create_index(op.f('ix_market_prices_price_date'), 'market_prices', ['price_date'], unique=False)
    op.create_table('vet_consultations',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('vet_name', sa.String(length=255), nullable=True),
    sa.Column('vet_phone', sa.String(length=50), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_vet_consultations_farmer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_vet_consultations_flock_id_flocks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vet_consultations'))
    )
    op.create_index(op.f('ix_vet_consultations_farmer_id'), 'vet_consultations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_vet_consultations_visit_date'), 'vet_consultations', ['visit_date'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vet_consultations_visit_date'), table_name='vet_consultations')
    op.drop_index(op.f('ix_vet_consultations_farmer_id'), table_name='vet_consultations')
    op.drop_table('vet_consultations')
    op.drop_index(op.f('ix_market_prices_price_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_county'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
