"""Migrate amounts to decimal and remove measurement_date

Revision ID: d4df720dd8fe
Revises: e4a3b8c9d0f1
Create Date: 2026-04-05 17:09:08.215796

"""
from alembic import op
import sqlalchemy as sa


revision = 'd4df720dd8fe'
down_revision = 'e4a3b8c9d0f1'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing defaults that conflict with the cast
    op.alter_column('subscription_plans', 'monthly_price', server_default=None)
    op.alter_column('subscription_plans', 'yearly_price', server_default=None)

    op.alter_column('subscription_plans', 'monthly_price',
               existing_type=sa.VARCHAR(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using='monthly_price::numeric(10,2)')
    op.alter_column('subscription_plans', 'yearly_price',
               existing_type=sa.VARCHAR(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False,
               postgresql_using='yearly_price::numeric(10,2)')
    
    # Re-apply new decimal defaults
    op.alter_column('subscription_plans', 'monthly_price', server_default=sa.text('0.00'))
    op.alter_column('subscription_plans', 'yearly_price', server_default=sa.text('0.00'))

    op.alter_column('subscriptions', 'amount',
               existing_type=sa.VARCHAR(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True,
               postgresql_using='amount::numeric(10,2)')
    op.add_column('users', sa.Column('county', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_county'), 'users', ['county'], unique=False)
    op.drop_index(op.f('ix_weight_measurement_events_measurement_date'), table_name='weight_measurement_events')
    op.create_index('ix_weight_measurement_events_event_date', 'weight_measurement_events', ['event_date'], unique=False)
    op.drop_column('weight_measurement_events', 'measurement_date')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weight_measurement_events', sa.Column('measurement_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index('ix_weight_measurement_events_event_date', table_name='weight_measurement_events')
    op.create_index(op.f('ix_weight_measurement_events_measurement_date'), 'weight_measurement_events', ['measurement_date'], unique=False)
    op.drop_index(op.f('ix_users_county'), table_name='users')
    op.drop_column('users', 'county')
    op.alter_column('subscriptions', 'amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('subscription_plans', 'yearly_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::character varying"))
    op.alter_column('subscription_plans', 'monthly_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::character varying"))
    op.drop_column('expenditures', 'checkout_request_id')
    # ### end Alembic commands ###
