"""Add preferences to users

Revision ID: d5bc38ca6bd5
Revises: 3f0262fe06e5
Create Date: 2025-12-08 16:41:16.057900

"""
from alembic import op
import sqlalchemy as sa


revision = 'd5bc38ca6bd5'
down_revision = '3f0262fe06e5'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###
