"""Add_notes_to_mortality_event

Revision ID: da1afc939ab6
Revises: 5091c024f4b4
Create Date: 2025-12-07 12:19:43.373460

"""
from alembic import op
import sqlalchemy as sa


revision = 'da1afc939ab6'
down_revision = '5091c024f4b4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mortality_events', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mortality_events', 'notes')
    # ### end Alembic commands ###
