"""Add farm_member

Revision ID: e3e9aeb3106c
Revises: fbd6ee72c5a9
Create Date: 2026-03-22 13:29:55.323290

"""
from alembic import op
import sqlalchemy as sa


revision = 'e3e9aeb3106c'
down_revision = 'fbd6ee72c5a9'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_members',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_members_farm_id_farms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_farm_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_members'))
    )
    op.create_index(op.f('ix_farm_members_farm_id'), 'farm_members', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_members_user_id'), 'farm_members', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_members_user_id'), table_name='farm_members')
    op.drop_index(op.f('ix_farm_members_farm_id'), table_name='farm_members')
    op.drop_table('farm_members')
    # ### end Alembic commands ###
