"""Add people models

Revision ID: e4c283e9ade4
Revises: d5bc38ca6bd5
Create Date: 2025-12-08 21:38:40.209031

"""
from alembic import op
import sqlalchemy as sa


revision = 'e4c283e9ade4'
down_revision = 'd5bc38ca6bd5'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('customer_type', sa.Enum('WHOLESALE', 'RETAIL', 'OTHER', name='customertype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    op.create_table('employees',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'WORKER', 'VET', 'OTHER', name='employeerole'), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('FEED', 'CHICKS', 'MEDICINE', 'EQUIPMENT', 'OTHER', name='suppliercategory'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_suppliers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_user_id'), 'suppliers', ['user_id'], unique=False)
    op.add_column('expenditures', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expenditures_supplier_id'), 'expenditures', ['supplier_id'], unique=False)
    op.create_foreign_key(op.f('fk_expenditures_supplier_id_suppliers'), 'expenditures', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.add_column('sales', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_foreign_key(op.f('fk_sales_customer_id_customers'), 'sales', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sales_customer_id_customers'), 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_column('sales', 'customer_id')
    op.drop_constraint(op.f('fk_expenditures_supplier_id_suppliers'), 'expenditures', type_='foreignkey')
    op.drop_index(op.f('ix_expenditures_supplier_id'), table_name='expenditures')
    op.drop_column('expenditures', 'supplier_id')
    op.drop_index(op.f('ix_suppliers_user_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
