"""Add checkout_request_id to subscriptions

Revision ID: ea560e676485
Revises: 1b63a44a336f
Create Date: 2025-12-09 22:22:38.186210

"""
from alembic import op
import sqlalchemy as sa


revision = 'ea560e676485'
down_revision = '1b63a44a336f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('checkout_request_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_subscriptions_checkout_request_id'), 'subscriptions', ['checkout_request_id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_checkout_request_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'checkout_request_id')
    # ### end Alembic commands ###
