"""Initial_schema

Revision ID: f01c93fc1c84
Revises: 
Create Date: 2026-04-21 19:33:04.258820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f01c93fc1c84'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('price_per_kg', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_per_bird', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price_per_kg > 0', name=op.f('ck_market_prices_positive_price_per_kg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_prices'))
    )
    op.create_index(op.f('ix_market_prices_county'), 'market_prices', ['county'], unique=False)
    op.create_index(op.f('ix_market_prices_price_date'), 'market_prices', ['price_date'], unique=False)
    op.create_table('resources',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('monthly_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('yearly_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=True),
    sa.Column('show_discount', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans'))
    )
    op.create_index(op.f('ix_subscription_plans_plan_type'), 'subscription_plans', ['plan_type'], unique=True)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_config'))
    )
    op.create_index(op.f('ix_system_config_key'), 'system_config', ['key'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='FARMER', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_county'), 'users', ['county'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('biosecurity_checks',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_biosecurity_checks_farmer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biosecurity_checks'))
    )
    op.create_index(op.f('ix_biosecurity_checks_farmer_id'), 'biosecurity_checks', ['farmer_id'], unique=False)
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('customer_type', sa.Enum('WHOLESALE', 'RETAIL', 'OTHER', name='customertype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    op.create_table('employees',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'WORKER', 'VET', 'OTHER', name='employeerole'), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('farms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_farms_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farms'))
    )
    op.create_index(op.f('ix_farms_name'), 'farms', ['name'], unique=False)
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('minimum_stock', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_unit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('last_restocked', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventory_items_positive_quantity')),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_inventory_items_farmer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    op.create_index(op.f('ix_inventory_items_farmer_id'), 'inventory_items', ['farmer_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('mpesa_reference', sa.String(), nullable=True),
    sa.Column('checkout_request_id', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('billing_period', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_checkout_request_id'), 'subscriptions', ['checkout_request_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_mpesa_reference'), 'subscriptions', ['mpesa_reference'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('FEED', 'CHICKS', 'MEDICINE', 'EQUIPMENT', 'OTHER', name='suppliercategory'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_suppliers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_user_id'), 'suppliers', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings'))
    )
    op.create_index(op.f('ix_user_settings_key'), 'user_settings', ['key'], unique=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_table('farm_members',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_farm_members_farm_id_farms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_farm_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_members'))
    )
    op.create_index(op.f('ix_farm_members_farm_id'), 'farm_members', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_members_user_id'), 'farm_members', ['user_id'], unique=False)
    op.create_table('flocks',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('hatchery_source', sa.String(length=255), nullable=True),
    sa.Column('source_location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('initial_count', sa.Integer(), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('cost_per_bird', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_acquisition_cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'sold', 'culled', 'terminated')", name=op.f('ck_flocks_valid_status')),
    sa.CheckConstraint('initial_count > 0', name=op.f('ck_flocks_positive_initial_count')),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_flocks_farm_id_farms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_flocks_farmer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flocks'))
    )
    op.create_index(op.f('ix_flocks_farm_id'), 'flocks', ['farm_id'], unique=False)
    op.create_index(op.f('ix_flocks_farmer_id'), 'flocks', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_flocks_status'), 'flocks', ['status'], unique=False)
    op.create_table('inventory_history',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('quantity_change', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_inventory_history_inventory_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_history'))
    )
    op.create_index(op.f('ix_inventory_history_inventory_item_id'), 'inventory_history', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_history_user_id'), 'inventory_history', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('flock_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_alerts_flock_id_flocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_flock_id', 'alerts', ['flock_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_triggered_at', 'alerts', ['triggered_at'], unique=False)
    op.create_table('daily_checks',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('check_time', sa.Time(), nullable=True),
    sa.Column('temperature_celsius', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('chick_behavior', sa.String(length=50), nullable=True),
    sa.Column('litter_condition', sa.String(length=50), nullable=True),
    sa.Column('feed_level', sa.String(length=50), nullable=True),
    sa.Column('water_level', sa.String(length=50), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("chick_behavior IN ('normal', 'huddling', 'dispersed', 'panting', 'lethargic')", name=op.f('ck_daily_checks_valid_chick_behavior')),
    sa.CheckConstraint("feed_level IN ('full', 'adequate', 'low', 'empty')", name=op.f('ck_daily_checks_valid_feed_level')),
    sa.CheckConstraint("litter_condition IN ('dry', 'damp', 'wet', 'caked')", name=op.f('ck_daily_checks_valid_litter_condition')),
    sa.CheckConstraint("water_level IN ('full', 'adequate', 'low', 'empty')", name=op.f('ck_daily_checks_valid_water_level')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_daily_checks_flock_id_flocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_daily_checks_recorded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_checks')),
    sa.UniqueConstraint('flock_id', 'check_date', name='uq_flock_daily_check')
    )
    op.create_index(op.f('ix_daily_checks_check_date'), 'daily_checks', ['check_date'], unique=False)
    op.create_index(op.f('ix_daily_checks_flock_id'), 'daily_checks', ['flock_id'], unique=False)
    op.create_table('expenditures',
    sa.Column('flock_id', sa.UUID(), nullable=True),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('receipt_image', sa.String(length=255), nullable=True),
    sa.Column('mpesa_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=50), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_expenditures_positive_amount')),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_expenditures_farmer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_expenditures_flock_id_flocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_expenditures_inventory_item_id_inventory_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_expenditures_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenditures'))
    )
    op.create_index(op.f('ix_expenditures_farmer_id'), 'expenditures', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_expenditures_flock_id'), 'expenditures', ['flock_id'], unique=False)
    op.create_index(op.f('ix_expenditures_inventory_item_id'), 'expenditures', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_expenditures_supplier_id'), 'expenditures', ['supplier_id'], unique=False)
    op.create_table('feed_consumption_events',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=True),
    sa.Column('quantity_kg', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('cost_ksh', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("feed_type IN ('starter', 'grower', 'finisher')", name=op.f('ck_feed_consumption_events_valid_feed_type')),
    sa.CheckConstraint('quantity_kg > 0', name=op.f('ck_feed_consumption_events_positive_feed_quantity')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_feed_consumption_events_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_consumption_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_feed_consumption_events_event_id'))
    )
    op.create_index('ix_feed_consumption_events_event_date', 'feed_consumption_events', ['event_date'], unique=False)
    op.create_index('ix_feed_consumption_events_event_id', 'feed_consumption_events', ['event_id'], unique=True)
    op.create_index('ix_feed_consumption_events_flock_id', 'feed_consumption_events', ['flock_id'], unique=False)
    op.create_table('mortality_events',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=100), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('count > 0', name=op.f('ck_mortality_events_positive_mortality_count')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_mortality_events_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mortality_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_mortality_events_event_id'))
    )
    op.create_index('ix_mortality_events_event_date', 'mortality_events', ['event_date'], unique=False)
    op.create_index('ix_mortality_events_event_id', 'mortality_events', ['event_id'], unique=True)
    op.create_index('ix_mortality_events_flock_id', 'mortality_events', ['flock_id'], unique=False)
    op.create_table('sales',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_bird', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('mpesa_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=50), nullable=True),
    sa.Column('average_weight_grams', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_sales_positive_quantity')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_sales_positive_total_amount')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_sales_farmer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_sales_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales'))
    )
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_farmer_id'), 'sales', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_sales_flock_id'), 'sales', ['flock_id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_scheduled_tasks_flock_id_flocks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scheduled_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks'))
    )
    op.create_index(op.f('ix_scheduled_tasks_due_date'), 'scheduled_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_flock_id'), 'scheduled_tasks', ['flock_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_status'), 'scheduled_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_user_id'), 'scheduled_tasks', ['user_id'], unique=False)
    op.create_table('vaccination_events',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('disease_target', sa.String(length=100), nullable=False),
    sa.Column('administration_method', sa.String(length=50), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('administered_by', sa.String(length=255), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("administration_method IN ('drinking_water', 'eye_drop', 'injection', 'spray')", name=op.f('ck_vaccination_events_valid_administration_method')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_vaccination_events_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaccination_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_vaccination_events_event_id'))
    )
    op.create_index('ix_vaccination_events_event_date', 'vaccination_events', ['event_date'], unique=False)
    op.create_index('ix_vaccination_events_event_id', 'vaccination_events', ['event_id'], unique=True)
    op.create_index('ix_vaccination_events_flock_id', 'vaccination_events', ['flock_id'], unique=False)
    op.create_index('ix_vaccination_events_next_due_date', 'vaccination_events', ['next_due_date'], unique=False)
    op.create_table('vet_consultations',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('flock_id', sa.UUID(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('vet_name', sa.String(length=255), nullable=True),
    sa.Column('vet_phone', sa.String(length=50), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], name=op.f('fk_vet_consultations_farmer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_vet_consultations_flock_id_flocks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vet_consultations'))
    )
    op.create_index(op.f('ix_vet_consultations_farmer_id'), 'vet_consultations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_vet_consultations_visit_date'), 'vet_consultations', ['visit_date'], unique=False)
    op.create_table('weight_measurement_events',
    sa.Column('flock_id', sa.UUID(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('average_weight_grams', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_weight_grams', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('max_weight_grams', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('average_weight_grams > 0', name=op.f('ck_weight_measurement_events_positive_average_weight')),
    sa.CheckConstraint('sample_size > 0', name=op.f('ck_weight_measurement_events_positive_sample_size')),
    sa.ForeignKeyConstraint(['flock_id'], ['flocks.id'], name=op.f('fk_weight_measurement_events_flock_id_flocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_measurement_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_weight_measurement_events_event_id'))
    )
    op.create_index('ix_weight_measurement_events_event_date', 'weight_measurement_events', ['event_date'], unique=False)
    op.create_index('ix_weight_measurement_events_event_id', 'weight_measurement_events', ['event_id'], unique=True)
    op.create_index('ix_weight_measurement_events_flock_id', 'weight_measurement_events', ['flock_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weight_measurement_events_flock_id', table_name='weight_measurement_events')
    op.drop_index('ix_weight_measurement_events_event_id', table_name='weight_measurement_events')
    op.drop_index('ix_weight_measurement_events_event_date', table_name='weight_measurement_events')
    op.drop_table('weight_measurement_events')
    op.drop_index(op.f('ix_vet_consultations_visit_date'), table_name='vet_consultations')
    op.drop_index(op.f('ix_vet_consultations_farmer_id'), table_name='vet_consultations')
    op.drop_table('vet_consultations')
    op.drop_index('ix_vaccination_events_next_due_date', table_name='vaccination_events')
    op.drop_index('ix_vaccination_events_flock_id', table_name='vaccination_events')
    op.drop_index('ix_vaccination_events_event_id', table_name='vaccination_events')
    op.drop_index('ix_vaccination_events_event_date', table_name='vaccination_events')
    op.drop_table('vaccination_events')
    op.drop_index(op.f('ix_scheduled_tasks_user_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_status'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_flock_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_due_date'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_sales_flock_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_farmer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_mortality_events_flock_id', table_name='mortality_events')
    op.drop_index('ix_mortality_events_event_id', table_name='mortality_events')
    op.drop_index('ix_mortality_events_event_date', table_name='mortality_events')
    op.drop_table('mortality_events')
    op.drop_index('ix_feed_consumption_events_flock_id', table_name='feed_consumption_events')
    op.drop_index('ix_feed_consumption_events_event_id', table_name='feed_consumption_events')
    op.drop_index('ix_feed_consumption_events_event_date', table_name='feed_consumption_events')
    op.drop_table('feed_consumption_events')
    op.drop_index(op.f('ix_expenditures_supplier_id'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_inventory_item_id'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_flock_id'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_farmer_id'), table_name='expenditures')
    op.drop_table('expenditures')
    op.drop_index(op.f('ix_daily_checks_flock_id'), table_name='daily_checks')
    op.drop_index(op.f('ix_daily_checks_check_date'), table_name='daily_checks')
    op.drop_table('daily_checks')
    op.drop_index('ix_alerts_triggered_at', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_flock_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_inventory_history_user_id'), table_name='inventory_history')
    op.drop_index(op.f('ix_inventory_history_inventory_item_id'), table_name='inventory_history')
    op.drop_table('inventory_history')
    op.drop_index(op.f('ix_flocks_status'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_farmer_id'), table_name='flocks')
    op.drop_index(op.f('ix_flocks_farm_id'), table_name='flocks')
    op.drop_table('flocks')
    op.drop_index(op.f('ix_farm_members_user_id'), table_name='farm_members')
    op.drop_index(op.f('ix_farm_members_farm_id'), table_name='farm_members')
    op.drop_table('farm_members')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_key'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_suppliers_user_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_mpesa_reference'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_checkout_request_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_inventory_items_farmer_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_name'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_biosecurity_checks_farmer_id'), table_name='biosecurity_checks')
    op.drop_table('biosecurity_checks')
    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_county'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_config_key'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_subscription_plans_plan_type'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_market_prices_price_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_county'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
