"""Add ApiKey and update Alert

Revision ID: f2fe9e107929
Revises: e3e9aeb3106c
Create Date: 2026-03-22 15:25:16.089865

"""
from alembic import op
import sqlalchemy as sa


revision = 'f2fe9e107929'
down_revision = 'e3e9aeb3106c'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.add_column('alerts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_alerts_user_id_users'), 'alerts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_alerts_user_id_users'), 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'user_id')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
