"""add_farms_table

Revision ID: fbd6ee72c5a9
Revises: 61ac5c0148ab
Create Date: 2026-03-21 05:29:49.628377

"""
from alembic import op
import sqlalchemy as sa


revision = 'fbd6ee72c5a9'
down_revision = '61ac5c0148ab'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_farms_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farms'))
    )
    op.create_index(op.f('ix_farms_name'), 'farms', ['name'], unique=False)
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.add_column('flocks', sa.Column('farm_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_flocks_farm_id'), 'flocks', ['farm_id'], unique=False)
    op.create_foreign_key(op.f('fk_flocks_farm_id_farms'), 'flocks', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_flocks_farm_id_farms'), 'flocks', type_='foreignkey')
    op.drop_index(op.f('ix_flocks_farm_id'), table_name='flocks')
    op.drop_column('flocks', 'farm_id')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_name'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
