"""add_billing_period_to_subscriptions

Revision ID: fe04bcc53389
Revises: 6c42fc395c02
Create Date: 2026-03-26 13:47:14.781097

"""
from alembic import op
import sqlalchemy as sa


revision = 'fe04bcc53389'
down_revision = '6c42fc395c02'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('billing_period', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'billing_period')
    # ### end Alembic commands ###
